from sqlrules.compiler import Compiler, clear_model_cache, compile, flatten, notwhere, where
from sqlrules.constraints import pattern_text
from sqlrules.errors import (
    CapabilityError,
    ConfigurationError,
    InternalCompilerError,
    InvalidModelError,
    InvalidTranslatorError,
    MissingColumnError,
    PluginError,
    RegistryError,
    SQLRulesError,
    TranslatorError,
    UnsupportedConstraintError,
)
from sqlrules.integrations.pydantic import (
    ConversionEntry,
    ConversionReport,
    PydanticConversion,
    from_pydantic,
)
from sqlrules.ir import (
    CompilationContext,
    CompiledRules,
    Constraint,
    Diagnostic,
    FieldDescriptor,
    FieldResult,
    PatternSpec,
    PreparedValue,
    RuleField,
    SchemaSpec,
)
from sqlrules.markers import (
    ArrayContains,
    ArrayOverlap,
    ConstraintMarker,
    FullTextMatch,
    JsonContains,
    JsonHasKey,
    RangeContains,
    RangeOverlap,
)
from sqlrules.models import Field, RuleConfig, RuleSchema
from sqlrules.plugins import PLUGIN_API_VERSION, BackendProvider, SQLRulesPlugin
from sqlrules.translators import TranslatorRegistry, default_registry

__version__ = "2.0.0"

__all__ = [
    "PLUGIN_API_VERSION",
    "ArrayContains",
    "ArrayOverlap",
    "BackendProvider",
    "CapabilityError",
    "CompilationContext",
    "CompiledRules",
    "Compiler",
    "ConfigurationError",
    "ConversionEntry",
    "ConversionReport",
    "Constraint",
    "ConstraintMarker",
    "Diagnostic",
    "FieldDescriptor",
    "FieldResult",
    "Field",
    "FullTextMatch",
    "InternalCompilerError",
    "InvalidModelError",
    "InvalidTranslatorError",
    "JsonContains",
    "JsonHasKey",
    "MissingColumnError",
    "PatternSpec",
    "PreparedValue",
    "PluginError",
    "RangeContains",
    "RangeOverlap",
    "RegistryError",
    "RuleConfig",
    "RuleField",
    "RuleSchema",
    "SchemaSpec",
    "SQLRulesError",
    "SQLRulesPlugin",
    "TranslatorError",
    "TranslatorRegistry",
    "PydanticConversion",
    "UnsupportedConstraintError",
    "__version__",
    "clear_model_cache",
    "compile",
    "default_registry",
    "flatten",
    "from_pydantic",
    "notwhere",
    "pattern_text",
    "where",
]
